import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';

import { toolInputSchemas } from '../lib/webmcp/tool-schemas';

const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  validateFormats: false,
  code: { source: true, esm: true },
});

for (const [name, schema] of Object.entries(toolInputSchemas)) {
  ajv.addSchema(schema, name);
}

const code = standaloneCode(ajv, {
  validateGetLivingContext: 'get_living_context',
  validateStageLivingBrief: 'stage_living_brief',
  validateFindCompatibleRooms: 'find_compatible_rooms',
  validateCompareShortlist: 'compare_shortlist',
  validatePrepareIntroduction: 'prepare_introduction',
});
const browserCompatibleCode = code.replace(
  'const func1 = require("ajv/dist/runtime/ucs2length").default;',
  'const func1 = (value) => Array.from(value).length;',
);
if (browserCompatibleCode.includes('require(')) {
  throw new Error('Generated validators contain an unsupported CommonJS dependency.');
}
const outputDirectory = path.resolve('lib/webmcp/generated');
await mkdir(outputDirectory, { recursive: true });
await writeFile(
  path.join(outputDirectory, 'tool-validators.mjs'),
  `// Generated by scripts/generate-tool-validators.ts. Do not edit by hand.\n${browserCompatibleCode}\n`,
  'utf8',
);
